Bookstore/Bookstore/Controllers/BookStoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bookstore.Models;
using PagedList;
using PagedList.Mvc;

namespace Bookstore.Controllers
{
    public class BookStoreController : Controller
    {
        dbQLBANSACHDataContext data = new dbQLBANSACHDataContext();
        private List<SACH> Laysachmoi(int count)
        {
            return data.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        // GET: BookStore
        public ActionResult Index(int ? page)
        {
            int pageSize = 5;
            int pageNum = (page ?? 1);
            var sachmoi = Laysachmoi(15);
            return View(sachmoi.ToPagedList(pageNum,pageSize));
        }
        public ActionResult Chude()
        {
            var chude = from cd in data.CHUDEs select cd;
            return PartialView(chude);
        }
        public ActionResult Nhaxuatban()
        {
            var nhaxuatban = from nxb in data.NHAXUATBANs select nxb;
            return PartialView(nhaxuatban);
        }
        public ActionResult SPTheoChude (int id)
        {
            var sach = from s in data.SACHes where s.MaCD == id select s;
            return View(sach);
        }
        public ActionResult SPTheoNXB(int id)
        {
            var sach = from s in data.SACHes where s.MaNXB == id select s;
            return View(sach);
        }
        public ActionResult Details (int id )
        {
            var sach = from s in data.SACHes
                       where s.Masach == id
                       select s;
            return View(sach.Single());
        }
    }   
}

Bookstore/Bookstore/Views/BookStore/Chude.cshtml
@model IEnumerable<Bookstore.Models.CHUDE>
<p class="lead"> CHỦ ĐỀ </p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <li>
            <a href="@Url.Action("SPTheoChude","Bookstore",new { id = item.MaCD })" class="list-group-item">
                @item.TenChuDe
            </a>
        </li>
    }
</div>

Bookstore/Bookstore/Views/BookStore/Details.cshtml
@model Bookstore.Models.SACH

<style type="text/css">
    #Datmua a {
        clear: both;
        background-color: red;
        color: white;
        width: 120px;
        height: 35px;
        display: block;
        /*float: right;*/
        text-align: center;
        padding-top: 10px;
        text-decoration: none;
        font-weight: bold;
        margin-left:250px;
    }

    #Datmua a:hover {
        background: #808080;
        color: red;
    }
</style>
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>THÔNG TIN CHI TIẾT SÁCH</h2>
@*<h3>Tên sách : @Model.Tensach</h3>*@
<div>
    <div style="width:40px;float:left;border:#808080;border-color:azure">
        <img src="~/HinhSanPham/@Model.Hinhminhhoa" width ="200" />
    </div>        
    <div style="width:500px;float: left;padding-left:20px;text-align:left">
        <p style="margin-left:150px;font-weight:bold"> Tên sách : <span style="color:red;font-size:16px">@Model.Tensach</span></p>
        <p style="margin-left:150px;text-align:justify;font-weight:bold">Mô tả :<span style="font-weight:bold;color:red"> @Html.DisplayFor(model => model.Mota)</span>  </p>
        <p style="margin-left:150px;font-weight:bold">Gía bán: <span style="color:red;font-size:16px">@Model.Dongia VND</span></p>
    </div>
        
    <div id="Datmua">
         <a href="@Url.Action("Themgiohang","Giohang",new { @iMasach = Model.Masach,@strURl = Request.Url.ToString()})">
             ĐẶT MUA
         </a>
    </div>
</div>

Bookstore/Bookstore/Views/BookStore/Index.cshtml
@*<link href="~/Content/templatemo_style.css" rel="stylesheet" />*@
@using Bookstore.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<div id="templatemo_content">
    <h3 style="text-align:center;color:red"> Sách Mới</h3>
    <div class="row">
        @foreach (var sach in Model)
        {
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })">
                        <img alt="@sach.Tensach" src="~/HinhSanPham/@sach.Hinhminhhoa" width="200" />
                        <div>
                            <br />
                            <h4 style="text-align:left">
                                @sach.Tensach
                            </h4>
                            <p></p>

                        </div>
                        <div class="ratings">
                            @*<h3 style="color:yellow">*@
                            <p class="pull-right"> 15 reviews </p>
                            <p>
                                <span class="glyphicon glyphicon-star"> </span>
                                <span class="glyphicon glyphicon-star"> </span>
                                <span class="glyphicon glyphicon-star"> </span>
                                <span class="glyphicon glyphicon-star"> </span>
                                <span class="glyphicon glyphicon-star"> </span>
                            </p>
                            @*</h3>*@
                        </div>
                    </a>
                </div>
            </div>
        }
    </div>
</div>


<div class="MenuTrang">
    Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;
    @Html.PagedListPager(Model,page=>Url.Action("Index",new { page = page }))
</div>
<style>
    .MenuTrang{
        margin-left:530px;
        color : white;
        line-height: 0 normal;
    }
    .MenuTrang li{
        display : inline;
    }
</style>

Bookstore/Bookstore/Views/BookStore/Nhaxuatban.cshtml
@model IEnumerable<Bookstore.Models.NHAXUATBAN>
<p class="lead"> NHÀ XUẤT BẢN </p>
<div class="list-group">
    @foreach (var item in Model)
    {
        <li>
            <a href="@Url.Action("SPTheoNXB","Bookstore",new { id =item.MaNXB})" class="list-group-item">
                @item.TenNXB
            </a>
        </li>
    }
</div>

Bookstore/Bookstore/Views/BookStore/SPTheoChude.cshtml
@model IEnumerable<Bookstore.Models.SACH>
@{
    ViewBag.Title = "SPTheoChude";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h3 style="text-align:center;color:red"> SÁCH THEO CHỦ ĐỀ </h3>
<div class="row">
    @foreach (var sach in Model)
    {
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })">
                    <img alt="@sach.Tensach" src="~/HinhSanPham/@sach.Hinhminhhoa" width="200" />
                    <div>
                        <br />
                        <h4 style="text-align:left">
                            @sach.Tensach
                        </h4>
                        <p></p>

                    </div>
                    <div class="ratings">
                        @*<h3 style="color:yellow">*@
                        <p class="pull-right"> 15 reviews </p>
                        <p>
                            <span class="glyphicon glyphicon-star"> </span>
                            <span class="glyphicon glyphicon-star"> </span>
                            <span class="glyphicon glyphicon-star"> </span>
                            <span class="glyphicon glyphicon-star"> </span>
                            <span class="glyphicon glyphicon-star"> </span>
                        </p>
                        @*</h3>*@
                    </div>
                </a>
            </div>
        </div>
    }
</div>

Bookstore/Bookstore/Views/BookStore/SPTheoNXB.cshtml
@model IEnumerable<Bookstore.Models.SACH>
@{
    ViewBag.Title = "SPTheoNXB";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

    <h3 style="text-align:center;color:red"> SÁCH THEO NHÀ XUẤT BẢN </h3>
    <div class="row">
        @foreach (var sach in Model)
        {
            <div class="col-sm-4 col-lg-4 col-md-4">
                <div class="thumbnail">
                    <a href="@Url.Action("Details", "BookStore", new { id = sach.Masach })">
                        <img alt="@sach.Tensach" src="~/HinhSanPham/@sach.Hinhminhhoa" width="200" />
                        <div>
                            <br />
                            <h4 style="text-align:left">
                                @sach.Tensach
                            </h4>
                            <p></p>

                        </div>
                        <div class="ratings">
                            @*<h3 style="color:yellow">*@
                            <p class="pull-right"> 15 reviews </p>
                            <p>
                                <span class="glyphicon glyphicon-star"> </span>
                                <span class="glyphicon glyphicon-star"> </span>
                                <span class="glyphicon glyphicon-star"> </span>
                                <span class="glyphicon glyphicon-star"> </span>
                                <span class="glyphicon glyphicon-star"> </span>
                            </p>
                            @*</h3>*@
                        </div>
                    </a>
                </div>
            </div>
        }
    </div>